In [1]:
import numpy as np
import tensorflow as tf

matrix = tf.constant([[1, 2], [3, 4]])
matrix1 = tf.constant([[2, 4], [6, 8]])
print(matrix+matrix1)


tf.Tensor(
[[ 3  6]
 [ 9 12]], shape=(2, 2), dtype=int32)


In [2]:
vector1 = tf.constant([10, 10])
vector2 = tf.constant([20, 20])
print(vector1+vector2)

tf.Tensor([30 30], shape=(2,), dtype=int32)


In [3]:
x = [1, 2, 3, 4, 5]
y = 1
tf.add(x, y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6])>

In [4]:
x = tf.convert_to_tensor([1, 2, 3, 4, 5])
y = tf.convert_to_tensor(1)
x + y

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6])>

In [5]:
x = [1, 2, 3, 4, 5]
y = tf.constant([1, 2, 3, 4, 5])
tf.add(x, y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10])>

In [6]:
x = tf.constant([1, 2], dtype=tf.int8)
y = [2**7 + 1, 2**7 + 2]
tf.add(x, y)

<tf.Tensor: shape=(2,), dtype=int8, numpy=array([-126, -124], dtype=int8)>

In [7]:
x = np.ones(6).reshape(1, 2, 1, 3)
y = np.ones(6).reshape(2, 1, 3, 1)
tf.add(x, y).shape.as_list()

[2, 2, 3, 3]

In [8]:
x = np.ones([1, 2, 1, 4])
y = np.ones([3, 4])
tf.add(x, y).shape.as_list()

[1, 2, 3, 4]